'use client'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { littersApi, buyersApi, contractsApi, aiApi } from '@/lib/api'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import toast from 'react-hot-toast'
import { useAuthStore } from '@/lib/store'

export default function NewContractPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user } = useAuthStore()
  const [step, setStep] = useState<'form'|'generating'|'preview'>('form')
  const [generatedText, setGeneratedText] = useState('')
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({
    litter_id: searchParams.get('litter') ?? '',
    buyer_id: '',
    sale_price: '',
    deposit_amount: '',
    puppy_description: '',
    special_terms: '',
  })
  const set = (k: string, v: any) => setForm(f => ({...f,[k]:v}))

  const { data: litters } = useQuery({ queryKey:['litters'], queryFn: ()=>littersApi.list().then(r=>r.data) })
  const { data: buyers } = useQuery({ queryKey:['buyers'], queryFn: ()=>buyersApi.list().then(r=>r.data) })

  const handleGenerate = async () => {
    if (!user?.subscription_active) {
      toast.error('AI contract generation requires a Pro plan. Upgrade to continue.')
      return
    }
    setStep('generating')
    try {
      const res = await aiApi.generateContract({
        litter_id: form.litter_id || null,
        buyer_id: form.buyer_id || null,
        sale_price: form.sale_price ? Number(form.sale_price) : null,
        deposit_amount: form.deposit_amount ? Number(form.deposit_amount) : null,
        puppy_description: form.puppy_description || null,
        special_terms: form.special_terms || null,
      })
      setGeneratedText(res.data.contract_text)
      setStep('preview')
    } catch (err: any) {
      toast.error(err.response?.data?.detail || 'AI generation failed. Check your Anthropic API key.')
      setStep('form')
    }
  }

  const handleSave = async () => {
    setSaving(true)
    try {
      await contractsApi
      toast.success('Contract saved!')
      router.push('/dashboard/contracts')
    } catch { toast.error('Failed to save') }
    finally { setSaving(false) }
  }

  if (step === 'generating') return (
    <div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:16}}>
      <div className="spinner" style={{width:40,height:40}} />
      <p style={{color:'var(--ink-3)',fontSize:15}}>Claude is drafting your contract…</p>
      <p style={{color:'var(--ink-4)',fontSize:13}}>Breed-specific clauses, health guarantees, return policy</p>
    </div>
  )

  if (step === 'preview') return (
    <>
      <div className="topbar">
        <div>
          <div style={{display:'flex',alignItems:'center',gap:8}}>
            <div className="topbar-title">AI Contract Draft</div>
            <span className="ai-pill"><svg viewBox="0 0 24 24" fill="currentColor" width="11" height="11"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg> Generated by Claude</span>
          </div>
          <div className="topbar-sub">Review and send to buyer</div>
        </div>
        <div className="topbar-right">
          <button onClick={()=>setStep('form')} className="btn-ghost">Edit Details</button>
          <button onClick={handleSave} disabled={saving} className="btn-primary">{saving?'Saving…':'Save Contract →'}</button>
        </div>
      </div>
      <div className="page-body">
        <div style={{maxWidth:740}}>
          <div className="card" style={{padding:32}}>
            <div style={{background:'var(--sage-l)',border:'1px solid var(--sage)',borderRadius:'var(--r-lg)',padding:'12px 16px',marginBottom:24,display:'flex',alignItems:'center',gap:10}}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="var(--forest)"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
              <span style={{fontSize:13,color:'var(--forest)',fontWeight:500}}>AI-generated draft. Review all terms before sending.</span>
            </div>
            <pre style={{fontFamily:'var(--sans)',fontSize:14,lineHeight:1.7,color:'var(--ink-2)',whiteSpace:'pre-wrap',wordBreak:'break-word'}}>{generatedText}</pre>
          </div>
        </div>
      </div>
    </>
  )

  return (
    <>
      <div className="topbar">
        <div>
          <div style={{display:'flex',alignItems:'center',gap:8}}>
            <div className="topbar-title">Generate AI Contract</div>
            <span className="ai-pill"><svg viewBox="0 0 24 24" fill="currentColor" width="11" height="11"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg> Powered by Claude</span>
          </div>
          <div className="topbar-sub">Breed-specific, legally-informed sale contract</div>
        </div>
        <div className="topbar-right"><Link href="/dashboard/contracts" className="btn-ghost">Cancel</Link></div>
      </div>
      <div className="page-body">
        <div style={{maxWidth:640}}>
          <div className="card" style={{padding:24,marginBottom:16}}>
            <div className="section-label" style={{marginBottom:16}}>Contract Details</div>
            <div className="two-col">
              <div className="field">
                <label className="label">Litter</label>
                <select className="input" value={form.litter_id} onChange={e=>set('litter_id',e.target.value)}>
                  <option value="">Select litter…</option>
                  {litters?.map((l:any)=><option key={l.id} value={l.id}>{l.name ?? l.breed}</option>)}
                </select>
              </div>
              <div className="field">
                <label className="label">Buyer</label>
                <select className="input" value={form.buyer_id} onChange={e=>set('buyer_id',e.target.value)}>
                  <option value="">Select buyer…</option>
                  {buyers?.map((b:any)=><option key={b.id} value={b.id}>{b.full_name}</option>)}
                </select>
              </div>
            </div>
            <div className="two-col">
              <div className="field"><label className="label">Sale price ($)</label><input type="number" className="input" placeholder="2800" value={form.sale_price} onChange={e=>set('sale_price',e.target.value)} /></div>
              <div className="field"><label className="label">Deposit amount ($)</label><input type="number" className="input" placeholder="500" value={form.deposit_amount} onChange={e=>set('deposit_amount',e.target.value)} /></div>
            </div>
            <div className="field"><label className="label">Puppy description</label><input className="input" placeholder="e.g. Female golden, collar color red, born April 3" value={form.puppy_description} onChange={e=>set('puppy_description',e.target.value)} /></div>
            <div className="field"><label className="label">Special terms <span style={{color:'var(--ink-4)',fontWeight:400}}>(optional)</span></label><textarea className="input" rows={2} placeholder="e.g. Breeding rights retained, limited registration" value={form.special_terms} onChange={e=>set('special_terms',e.target.value)} style={{resize:'vertical'}} /></div>
          </div>

          {!user?.subscription_active && (
            <div style={{background:'var(--amber-f)',border:'1px solid var(--amber-l)',borderRadius:'var(--r-lg)',padding:'14px 18px',marginBottom:16,display:'flex',alignItems:'center',gap:12}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
              <div>
                <p style={{fontSize:14,fontWeight:600,color:'var(--amber)'}}>Pro plan required for AI contracts</p>
                <Link href="/dashboard/upgrade" style={{fontSize:13,color:'var(--amber)',textDecoration:'none'}}>Upgrade now →</Link>
              </div>
            </div>
          )}

          <button onClick={handleGenerate} className="btn-primary" style={{fontSize:15,padding:'12px 28px'}}>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
            Generate with Claude
          </button>
        </div>
      </div>
    </>
  )
}
