'use client'
import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { littersApi, buyersApi, contractsApi, aiApi } from '@/lib/api'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import toast from 'react-hot-toast'
import { useAuthStore } from '@/lib/store'

export default function NewContractPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user } = useAuthStore()
  const qc = useQueryClient()
  const [step, setStep] = useState<'form'|'generating'|'preview'>('form')
  const [generatedText, setGeneratedText] = useState('')
  const [contractId, setContractId] = useState<string|null>(null)
  const [saving, setSaving] = useState(false)
  const [sending, setSending] = useState(false)
  const [form, setForm] = useState({
    litter_id: searchParams.get('litter') ?? '',
    buyer_id: searchParams.get('buyer') ?? '',
    sale_price: '',
    deposit_amount: '',
    puppy_description: '',
    special_terms: '',
  })
  const set = (k: string, v: any) => setForm(f => ({...f, [k]: v}))

  const { data: litters } = useQuery({ queryKey:['litters'], queryFn:()=>littersApi.list().then(r=>r.data) })
  const { data: buyers } = useQuery({ queryKey:['buyers'], queryFn:()=>buyersApi.list().then(r=>r.data) })

  const handleGenerate = async () => {
    if (!user?.subscription_active) {
      toast.error('AI contract generation requires a Pro plan.')
      return
    }
    if (!form.buyer_id) {
      toast.error('Please select a buyer first')
      return
    }
    setStep('generating')
    try {
      const res = await aiApi.generateContract({
        litter_id: form.litter_id || null,
        buyer_id: form.buyer_id,
        sale_price: form.sale_price ? Number(form.sale_price) : null,
        deposit_amount: form.deposit_amount ? Number(form.deposit_amount) : null,
        puppy_description: form.puppy_description || null,
        special_terms: form.special_terms || null,
      })
      setGeneratedText(res.data.contract_text)
      // If backend returns a saved contract ID, capture it
      if (res.data.contract_id) setContractId(res.data.contract_id)
      setStep('preview')
    } catch (err: any) {
      const detail = err.response?.data?.detail || err.message || 'AI generation failed'
      toast.error(detail.includes('API') ? 'Add your Anthropic API key in Railway to enable AI contracts.' : detail)
      setStep('form')
    }
  }

  const handleSave = async () => {
    if (!form.buyer_id) { toast.error('Select a buyer to save this contract'); return }
    setSaving(true)
    try {
      const payload: any = {
        buyer_id: form.buyer_id,
        content: generatedText,
        status: 'draft',
      }
      if (form.sale_price) payload.sale_price = Number(form.sale_price)
      if (form.litter_id) payload.litter_id = form.litter_id
      if (form.deposit_amount) payload.deposit_amount = Number(form.deposit_amount)

      const res = await contractsApi.create(payload)
      setContractId(res.data.id)
      qc.invalidateQueries({ queryKey: ['contracts'] })
      toast.success('Contract saved as draft!')
      router.push('/dashboard/contracts')
    } catch (err: any) {
      toast.error(err.response?.data?.detail || 'Failed to save contract')
    } finally { setSaving(false) }
  }

  const handleSend = async () => {
    if (!contractId) {
      toast.error('Save the contract first before sending')
      return
    }
    setSending(true)
    try {
      await contractsApi.send(contractId)
      toast.success('Contract sent to buyer!')
      router.push('/dashboard/contracts')
    } catch (err: any) {
      toast.error(err.response?.data?.detail || 'Failed to send contract')
    } finally { setSending(false) }
  }

  if (step === 'generating') return (
    <div style={{minHeight:'100vh',display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:20}}>
      <div style={{width:56,height:56,borderRadius:'50%',background:'var(--sage-l)',display:'flex',alignItems:'center',justifyContent:'center'}}>
        <div className="spinner" style={{width:28,height:28}}/>
      </div>
      <div style={{textAlign:'center'}}>
        <p style={{color:'var(--ink-2)',fontSize:17,fontWeight:600,marginBottom:6}}>Claude is drafting your contract…</p>
        <p style={{color:'var(--ink-4)',fontSize:14}}>Breed-specific clauses · Health guarantees · Return policy</p>
      </div>
    </div>
  )

  if (step === 'preview') return (
    <>
      <div className="topbar">
        <div>
          <div style={{display:'flex',alignItems:'center',gap:8}}>
            <div className="topbar-title">AI Contract Draft</div>
            <span className="ai-pill"><svg viewBox="0 0 24 24" fill="currentColor" width="11" height="11"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>Generated by Claude</span>
          </div>
          <div className="topbar-sub">Review carefully before sending</div>
        </div>
        <div className="topbar-right">
          <button onClick={()=>setStep('form')} className="btn-ghost">← Edit Details</button>
          <button onClick={handleSave} disabled={saving} className="btn-ghost">
            {saving?'Saving…':'Save Draft'}
          </button>
          <button onClick={handleSend} disabled={sending||!contractId} className="btn-primary">
            {sending?'Sending…':'Save & Send →'}
          </button>
        </div>
      </div>
      <div className="page-body">
        <div style={{maxWidth:740}}>
          <div className="card" style={{padding:32}}>
            <div style={{background:'var(--sage-l)',border:'1px solid var(--sage)',borderRadius:'var(--r-lg)',padding:'12px 16px',marginBottom:24,display:'flex',alignItems:'center',gap:10}}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="var(--forest)"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
              <span style={{fontSize:13,color:'var(--forest)',fontWeight:500}}>AI-generated draft. Review all terms before sending to buyer.</span>
            </div>
            <pre style={{fontFamily:'var(--sans)',fontSize:13.5,lineHeight:1.8,color:'var(--ink-2)',whiteSpace:'pre-wrap',wordBreak:'break-word'}}>{generatedText}</pre>
          </div>
          <div style={{display:'flex',gap:10,marginTop:16}}>
            <button onClick={handleSave} disabled={saving} className="btn-primary">
              {saving?'Saving…':'Save as Draft'}
            </button>
            <button onClick={handleSend} disabled={sending||!contractId} className="btn-primary" style={{background:'linear-gradient(135deg,#1e4d7a,#2563eb)'}}>
              {sending?'Sending…':'Send to Buyer →'}
            </button>
          </div>
        </div>
      </div>
    </>
  )

  return (
    <>
      <div className="topbar">
        <div>
          <div style={{display:'flex',alignItems:'center',gap:8}}>
            <div className="topbar-title">Generate AI Contract</div>
            <span className="ai-pill"><svg viewBox="0 0 24 24" fill="currentColor" width="11" height="11"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>Claude</span>
          </div>
          <div className="topbar-sub">Breed-specific, legally-informed sale contract</div>
        </div>
        <div className="topbar-right"><Link href="/dashboard/contracts" className="btn-ghost">Cancel</Link></div>
      </div>
      <div className="page-body">
        <div style={{maxWidth:640}}>
          <div className="card" style={{padding:24,marginBottom:16}}>
            <div className="section-label" style={{marginBottom:16}}>Contract Details</div>
            <div className="two-col">
              <div className="field">
                <label className="label">Litter <span style={{color:'var(--ink-4)',fontWeight:400}}>(optional)</span></label>
                <select className="input" value={form.litter_id} onChange={e=>set('litter_id',e.target.value)}>
                  <option value="">Select litter…</option>
                  {litters?.map((l:any)=><option key={l.id} value={l.id}>{l.name??l.breed}</option>)}
                </select>
              </div>
              <div className="field">
                <label className="label">Buyer *</label>
                <select className="input" value={form.buyer_id} onChange={e=>set('buyer_id',e.target.value)} required>
                  <option value="">Select buyer…</option>
                  {buyers?.map((b:any)=><option key={b.id} value={b.id}>{b.full_name}</option>)}
                </select>
              </div>
            </div>
            <div className="two-col">
              <div className="field"><label className="label">Sale price ($) *</label><input type="number" className="input" placeholder="2800" value={form.sale_price} onChange={e=>set('sale_price',e.target.value)} /></div>
              <div className="field"><label className="label">Deposit ($)</label><input type="number" className="input" placeholder="500" value={form.deposit_amount} onChange={e=>set('deposit_amount',e.target.value)} /></div>
            </div>
            <div className="field"><label className="label">Puppy description</label><input className="input" placeholder="e.g. Female golden, red collar, born April 3" value={form.puppy_description} onChange={e=>set('puppy_description',e.target.value)} /></div>
            <div className="field"><label className="label">Special terms <span style={{color:'var(--ink-4)',fontWeight:400}}>(optional)</span></label><textarea className="input" rows={2} placeholder="e.g. Breeding rights retained, limited registration" value={form.special_terms} onChange={e=>set('special_terms',e.target.value)} style={{resize:'vertical'}}/></div>
          </div>

          {!user?.subscription_active && (
            <div style={{background:'var(--amber-f)',border:'1px solid rgba(200,117,26,.3)',borderRadius:'var(--r-lg)',padding:'14px 18px',marginBottom:16,display:'flex',alignItems:'center',gap:12}}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
              <div>
                <p style={{fontSize:14,fontWeight:600,color:'var(--amber)'}}>Pro plan required for AI contracts</p>
                <Link href="/dashboard/upgrade" style={{fontSize:13,color:'var(--amber)',textDecoration:'none',fontWeight:500}}>Upgrade now →</Link>
              </div>
            </div>
          )}

          <button onClick={handleGenerate} className="btn-primary" style={{fontSize:15,padding:'12px 28px'}}>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
            Generate with Claude
          </button>
        </div>
      </div>
    </>
  )
}
